### ISSUE TITLE
Create navbar and footer

### ISSUE THREAD

**Issue by ambarvm** [supercoww/prayatna-app#1]
Create navbar and footer components in separate PHP files in the `/components` directory. The navbar file should contain a fixed navbar and a side-nav.

**Comment by nitink4472** [comment]
> The navbar and the footer PHP files are already there in the directory. Do i have to make a separate one in the same directory? Or include my code in it ?
> 

You have to include your code in the existing files. Are you interested in working on this issue?

**Comment by nitink4472** [comment]
Working !!

**Comment by nitink4472** [comment]
Tell me how does the navbar look like?

**Comment by nitink4472** [comment]
I mean the css

**Comment by ambarvm** [comment]
You have to design the navbar and footer by yourself. You can check examples from materializecss.com. For the links to be added on navbar, take a look at other issues.

**Comment by nitink4472** [comment]
> You have to design the navbar and footer by yourself. You can check examples from materializecss.com. For the links to be added on navbar, take a look at other issues.

And what are the links to be there on a footer and on the navbar?

**Comment by nitink4472** [comment]
> You have to include your code in the existing files. Are you interested in working on this issue?
Yes i am working on this first !

**Comment by nitink4472** [comment]
> > The navbar and the footer PHP files are already there in the directory. Do i have to make a separate one in the same directory? Or include my code in it ?
> 
> You have to include your code in the existing files. Are you interested in working on this issue?

Yes i'm working on this first !
