### ISSUE TITLE
Add edit functionality to new match page

### ISSUE THREAD

**Issue by ambarvm** [supercoww/prayatna-app#19]
The new match page should check for the query string parameter `id` in the URL.
Example URL: `https://localhost/newmatch.php?id=dqw4w9wgxcq`
See https://stackoverflow.com/questions/979975/how-to-get-the-value-from-the-get-parameters

If a valid id exists, get event data for that id from firestore and fill it in the form inputs. In this case, submitting the form should update the existing document instead of creating a new one.

If the id does not exist or is invalid, the form fields should remain empty and create a new document on submission.

**Comment by nitink4472** [comment]
I'm working on this.
