### ISSUE TITLE
Create teams page

### ISSUE THREAD

**Issue by ambarvm** [supercoww/prayatna-app#2]
Create UI for a Teams page showing each team's
- Name
- Logo
- A group photo
- List of points in each sport
- List of team members

**Comment by parthjoshi2001** [comment]
I have to make separate pages for each team ?

**Comment by ambarvm** [comment]
@parthjoshi2001 you have to make a single page with some placeholder data. Later, we will fetch the team info from firestore and display it using javascript.

**Comment by parthjoshi2001** [comment]
fromm where can I get group photos and logos of the teams

**Comment by ambarvm** [comment]
I will arrange them for you. Use any stock photos from the internet for now.

**Comment by parthjoshi2001** [comment]
what does placeholder data means ?

**Comment by ambarvm** [comment]
Some made up data which you will replace later.
