### ISSUE TITLE
Create All Sports page

### ISSUE THREAD

**Issue by ambarvm** [supercoww/prayatna-app#3]
Create an **All Sports** page showing a list of sports. Clicking on a sport should show a list of past matches of the selected sport on a separate page.

**Comment by harshitjajodia20** [comment]
i am interested to work on this page.

**Comment by ambarvm** [comment]
@harshitjajodia20 you can start working on this issue. You will have to create 2 pages, one for the list of sports and another for showing a list of past matches. The match list should show the following for each match:
- Date
- Participating Teams
- Scores

If you have some more ideas for these pages. You can discuss them here.
