### ISSUE TITLE
Create live matches page

### ISSUE THREAD

**Issue by ambarvm** [supercoww/prayatna-app#4]
Create UI for a live matches page showing scorecards of ongoing matches.

**Comment by harshil1509** [comment]
I would like to work on this

**Comment by ambarvm** [comment]
@harshil1509 you can start working. The score cards should contain the:
- team names
- team logos
- scores
- additional information (like toss winner)

You may need to design separate cards for some sports (e.g. chess). Start with the Frontend. Use index.php as a template.
